name: PHIStruct-experiments
channels:
    - conda-forge
dependencies:
    - python=3.10
    - tqdm=4.65.0
    - regex=2022.7.9
    - nltk=3.8.1
    - biopython=1.78
    - ete3=3.1.3
    - pandas=1.5.3
    - numpy=1.24.3
    - scipy=1.9.3
    - h5py=3.10.0
    - scikit-learn=1.2.0
    - imbalanced-learn=0.11.0
    - xgboost=1.7.6
    - matplotlib=3.7.1
    - seaborn=0.12.2
    - pip=24.0
    - pip:
          - --extra-index-url https://download.pytorch.org/whl/cu117
          - torch==1.13.1+cu117
